# themes from https://github.com/alacritty/alacritty-theme

import = ["/home/mike/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"]

[font]
size = 13

#[font.normal]
#family = "Ubuntu Nerd Font"

[window]
decorations = "none"

[window.padding]
#x = 7
#y = 0
